---

- name: setting the stripes based on number of disks passed 
  set_fact: 
   stripe_value: "{{ item.value }}"
  when:
  - item.key == "{{ file_system_name  }}"
  with_dict: "{{ my_stripes_list }}"

- set_fact:
   device_pv: ""
- name: populating a variable for vg creation
  set_fact:
    device_pv: "{{ device_pv + ',' +  item.key }}"
  when:
  - item.value == file_system_name
  with_dict: "{{ pv_listing }}"

- name: substituting , in data_pv variable to form a string for vg creation 
  shell: echo {{ device_pv }} | sed 's/^,//g'
  register: device_for_vg

- set_fact:
   file_system_vg: "{{ item.key }}vg"
  when:
  - item.value ==  file_system_name 
  with_dict: "{{ my_vg_list }}"

- set_fact:
   file_system_lv: "{{ item.key }}lv"
  when:
  - item.value == file_system_name
  with_dict: "{{ my_vg_list }}"

- set_fact:
   file_system_mount_point: "{{ item.key }}"
  when:
  - item.value == file_system_name
  with_dict: "{{ my_mount_point }}"
# need a temporary list variable to assign pv_create_list to NULL again...this section create  a list which is based on file_system_name value
- set_fact: pv_temp="{{ pv_temp | default([]) }}"
- set_fact: pv_create_list="{{ pv_temp | default([])  }}"
- set_fact: pv_create_list="{{ pv_create_list | default([])  }}  + ['{{ item.key }}']"
  when:
  - item.value == file_system_name
  with_dict: "{{ pv_listing }}"

- import_tasks: ./file_system_creation.yml

