---


- name: task for creating pvs 
  shell: pvcreate {{ item }}
  with_items: "{{ pv_create_list }}" 

- name:  Manage LVM volume group(s)
  lvg:
    vg: "{{file_system_vg}}"
    pvs: "{{device_for_vg.stdout}}"
    state: present   

- name: LVS | create LV  
  lvol:
    vg: "{{ file_system_vg }}" 
    lv: "{{ file_system_lv }}" 
    size: 100%FREE
    opts: --stripes {{ stripe_value }}
    state: present

- name: Create directory {{ file_system_mount_point }} does not exist
  file:
    path: "{{ file_system_mount_point }}" 
    state: directory
    mode: '0755'

- name:  create filesystems 
  filesystem:
    fstype: xfs 
    dev: "/dev/mapper/{{file_system_vg}}-{{ file_system_lv }}"
    state: present

- name: mount the lv on {{ file_system_mount_point }}
  mount:
    path: "{{ file_system_mount_point }}" 
    src: "/dev/mapper/{{file_system_vg}}-{{ file_system_lv }}" 
    fstype: xfs 
    state: mounted



