---
#- include_vars: /root/variable_file.txt

- name: for loop, to manipulate pv listing. #We use this loop to distribute pvs for names provided and use them later for filesystem creation.
  shell: i=0; while [[ $i -lt {{ item.1 }} ]]; do echo {{ item.0 }} ; let i=i+1; done
  register: loop_for_wwn
  with_together:
  - "{{ disks_configuration.names | map('trim') | list }}"
  - "{{  disks_configuration.counts | map('trim') | list }}"
- set_fact:
    tmp_wwn_list="{{ tmp_wwn_list | default([]) }} + {{ item.stdout_lines | list|flatten }}"
  loop: "{{ loop_for_wwn.results }}"

# lets create a dict with pv and its type
- set_fact:
   pv_listing_dm: "{{ pv_listing_dm | default({}) |  combine({ item.0: item.1  })}}"
  with_together:
  - "{{ disks_configuration.disks_wwn | map('trim') | list  }}"
  - "{{ tmp_wwn_list }}"

- debug: msg="{{ pv_listing_dm }}"



- copy: content="{{ pv_listing_dm  }}" dest=/root/tmp_file
- shell: "cat /root/tmp_file | tr [{},] '\n' | tee /root/tmp_file_mod"
- shell: "cat /root/tmp_file_mod | sed 's/ //g' | sed 's/\"//g' | grep {{ item }} | sed 's/:{{ item }}//g' | tr '\n' ',' | sed 's/,$//g'"
  register: tmp_wwn_var
  loop: "{{ disks_configuration.names | map('trim') | list }}"
- debug: var=tmp_wwn_var

- set_fact:
    wwn_list="{{ wwn_list | default([]) }} + {{ item.stdout_lines | list|flatten }}"
  loop: "{{ tmp_wwn_var.results }}"
- debug: var=wwn_list

# to create stripes list dict
- set_fact:
     disks_config_mod: "{{ disks_config_mod | default([]) + [{ 'name': item.0, 'count' : item.1, 'path' : item.2, 'wwn' : item.3 }] }}"
  with_together:
  - "{{ disks_configuration.names | map('trim') | list }}"
  - "{{ disks_configuration.counts | map('trim') | list }}"
  - "{{ disks_configuration.paths | map('trim') | list }}"
  - "{{ wwn_list }}"

- name: Display the Dictionaries
  debug: var=disks_config_mod


- include_tasks: ../roles/fs_creation_sles/tasks/main.yml 
  with_items: 
  - "{{ disks_config_mod }}" 
  loop_control:
    loop_var: file_system_list


## to remove temp file created. 
- name: remove temp file created during execution 
  file: 
   state: absent
   path: "{{ item }}"
  with_items:
  - /root/tmp_file
  - /root/tmp_file_mod 
  
