---
# this role configures RHEL lpar for sap installation.

# this is an optional requirement. If inventory_ip is passed as a variable, this task is executed. 
- name: Add /etc/hosts resolution for the host itself
  lineinfile:
   dest: /etc/hosts
   regexp: "^{{ ansible_hostname }}"
   line: "{{ inventory_ip }} {{ ansible_hostname }}"
   state: "present"
  when: inventory_ip is defined

# subscribing to RHEL and setting release to {{ rhel_subcription.release }}
- name: Subscribing to RHEL and setting release to {{ rhel_subcription.release }}
  shell: |
   subscription-manager register --username {{ rhel_subcription.username }} --password {{ rhel_subcription.password }} --auto-attach --force
   subscription-manager release --set={{ rhel_subcription.release }}

# Add repos for installing RHEL packages required for SAP installation
- name: Adding RHEL repos
  shell: subscription-manager repos --enable="rhel-8-for-ppc64le-baseos-e4s-rpms" --enable="rhel-8-for-ppc64le-appstream-e4s-rpms" --enable="rhel-8-for-ppc64le-sap-solutions-e4s-rpms" --enable="rhel-8-for-ppc64le-sap-netweaver-e4s-rpms" --enable="rhel-8-for-ppc64le-highavailability-e4s-rpms"

# multipathd daemon is checked whether its up or not. If not, it is started. 
- name: Ensure multipathd daemon is running
  service:
   name: multipathd
   state: started 

# For modification on network interfaces, create a dictionary of interfaces
- name: Create interfaces dictionary
  set_fact:
   interfaces: "{{ interfaces | default({}) | combine( {item: hostvars[ inventory_hostname ] ['ansible_' + item ]} ) }}"
  with_items: "{{ ansible_interfaces | replace('-', '_') }}"

# activate jumbo frames and MTU for all network interfaces except management interfaces 
- name: Activate jumboframes for all networks except management interface and lo and activate tso
  shell: "ip link set dev {{ item.key }} mtu 9000; ethtool -K {{ item.key }} tso on"
  with_dict: "{{ interfaces }}"
  when:
  - "item.value.ipv4.address is defined"
  - "item.value.ipv4.address != host_ip"
  - "item.key != 'lo'"
  - "item.value.mtu != 9000"

# to make the above changes persistent across reboot.
- name: Set jumboframes permanently so it is valid after reboots for all networks except eth0 and lo
  lineinfile:
   dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.key }}"
   regexp: "^MTU"
   line: "MTU='9000'"
  with_dict: "{{ interfaces }}"
  when:
  - "item.value.ipv4.address is defined"
  - "item.value.ipv4.address != host_ip" 
  - "item.key != 'lo'"
  - "item.value.mtu != 9000"


- name: Set ETHTOOL_OPT On permanently so it is valid after reboots for all networks except eth0 and lo
  lineinfile:
   dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.key }}"
   regexp: "^ETHTOOL_OPT"
   line: "ETHTOOL_OPT='-K {{ item.key }} tso on'"
  with_dict: "{{ interfaces }}"
  when:
  - "item.value.ipv4.address is defined"
  - "item.value.ipv4.address != host_ip" 
  - "item.key != 'lo'"
  - "item.value.mtu != 9000"

# to reinforce changes in current boot 
- name: Restart network 
  service:
   name: NetworkManager 
   state: restarted

# to Insure that NFS and rpcbind daemon are up. 
- name: Ensure NFS client is running
  service:
   name: nfs-client.target
   state: started
   enabled: yes

- name: Ensure rpcbind is running
  service:
   name: rpcbind
   state: started
   enabled: yes