---
- import_tasks: ../../../roles/read_var/tasks/main.yaml
- include_tasks: ../../../tasks/file_system_set_fact.yaml 
  vars:
   type_fs: "{{ inner_item }}" 
  with_items: 
  - "{{ disks_configuration.names }}" 
  loop_control:
    loop_var: inner_item
